micronaut:
  application:
    name: keyManager
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/keymanager
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    dialect: postgres

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

