micronaut:
  application:
    name: keyManager

datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5432/keymanager`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER_NAME:`postgres`}
    password: ${DB_PASSWORD:`postgres`}
    dialect: postgres

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update

itau:
  contas:
    url: ${URL_CONTAS_ITAU:`http://localhost:9091`}

bcb:
  pix:
    url: ${URL_BCB_PIX:`http://localhost:8082`}

